
# Copyright 2017-2020 Dirk Brenken (dev@brenken.org)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI TechnoSkver RTR02 UI module
LUCI_DESCRIPTION:=UI module for Double SIM management for Skw92A with Sim7600 modem integration.
LUCI_TYPE:=mod

PKG_NAME:=luci-mod-rosze-ui
PKG_VERSION:=3.0.1
PKG_RELEASE:=20230614
PKG_LICENSE:=GPL-3.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
